version: '3.8'
services:
  v1:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./app:/app/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development